#backend/Dockerfile
FROM tensorflow/tensorflow:latest

# Maintainer info
LABEL maintainer="ysf.safi@gmail.com"
WORKDIR /app

COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "main.py"]
