#backend/Dockerfile
FROM python:3.10.1-slim



# Maintainer info
LABEL maintainer="ysf.safi@gmail.com"

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow-aarch64 -f https://tf.kmtea.eu/whl/stable.html
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "main.py"]
